name: Test and build on push

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  tests:
    uses: ./.github/workflows/test.yaml
    needs: build
