name: Test and build on push

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  tests:
    uses: ./.github/workflows/test.yaml

  build:
    uses: ./.github/workflows/build.yaml
    needs: tests
