name: Publish Python Package

on:
  - workflow_call

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/download-artifact@v3
        with:
          name: jam-tool-package
          path: dist/

      - name: Publish packages
        run: make -e publish-test
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
