name: Test build and publish python release
on:
  push:
    tags-ignore:
      - '*.*.*a*'
      - '*.*.*b*'
      # - '*.*.*rc*'
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  tests:
    uses: ./.github/workflows/test.yaml
    needs: build

  publish:
    uses: ./.github/workflows/publish.yaml
    needs: build
    secrets:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
