name: Test build and publish python release
on:
  push:
    tags-ignore:
      # - '*.*.*a*'
      - '*.*.*b*'
      - '*.*.*rc*'
  workflow_dispatch: {}

jobs:
  tests:
    uses: ./.github/workflows/test.yaml

  build:
    uses: ./.github/workflows/build.yaml
    needs: tests

  publish:
    uses: ./.github/workflows/publish.yaml
    needs: build
